"""Render the missing Shanghai tiles and merge them with the existing ones -> out/tiles.js"""
import sys, json, io, base64, pickle, time, os, multiprocessing as mp
sys.path.insert(0, '..')
import build_tiles as B
pl = json.load(open('plan.json')); plan = {int(z): [tuple(t) for t in v] for z, v in pl['plan'].items()}
def load(n): return pickle.load(open(f'sh_{n}.pkl', 'rb'))
def merge(*ds):
    out = {k: [] for k in ('buildings', 'water', 'land', 'land_use', 'roads')}
    for d in ds:
        for k in out: out[k] += d[k]
    return out
G = {}                                              # data sets, shared with the worker processes (fork)
def work(job):
    z, x, y, key = job
    im = B.render(G[key], z, x, y); b = io.BytesIO(); im.save(b, 'WEBP', quality=66 if z >= 16 else 58, method=6)
    return f'{z}/{x}/{y}', base64.b64encode(b.getvalue()).decode()
if __name__ == '__main__':
    R1, R2 = load('R1'), load('R2'); G['R1'] = B.Data(R1); G['R12'] = B.Data(merge(R1, R2))
    comp_of = {}
    for c in pl['components']:
        n = c['name']; G[n] = B.Data(load(n))
    # which component owns each z15 tile: the bbox in WGS -> use the tile lists rebuilt from plan2.components()
    import plan2
    t15 = set(plan[15]) | {(x//2, y//2) for x, y in plan[16]}
    for i, comp in enumerate(sorted(plan2.components(t15), key=len, reverse=True)):
        for t in comp: comp_of[t] = f'cmp{i}'
    # trim: z13 only within 7 tiles (~30 km) of a spot and z14 within 3 tiles; z11/12 stay province-wide (nothing is ever blank)
    import plan as PL
    def near(z, r):
        N = 2**z; keep = set()
        for _, lat, lng in PL.spots:
            mx, my = PL.merc(lat, lng); cx, cy = int(mx*N), int(my*N)
            keep |= {(x, y) for x in range(cx-r, cx+r+1) for y in range(cy-r, cy+r+1)}
        return keep
    k13, k14 = near(13, 7), near(14, 3)
    plan[13] = [t for t in plan[13] if t in k13]; plan[14] = [t for t in plan[14] if t in k14]
    jobs = []
    for z in (16, 15, 14, 13, 12, 11):
        for x, y in plan[z]:
            key = 'R1' if z <= 13 else 'R12' if z == 14 else comp_of[(x >> (z-15), y >> (z-15))] if z == 16 else comp_of[(x, y)]
            jobs.append((z, x, y, key))
    print('jobs', len(jobs), flush=True); t0 = time.time(); new = {}
    with mp.get_context('fork').Pool(4) as pool:
        for i, (k, v) in enumerate(pool.imap_unordered(work, jobs, chunksize=4)):
            new[k] = v
            if i % 300 == 0: print(i, len(jobs), '%.0fs' % (time.time() - t0), flush=True)
    old = json.load(open('tiles_existing.json')); old.update({k: v for k, v in new.items() if k not in old})
    import collections
    size = collections.Counter(); cnt = collections.Counter()
    for k, v in new.items(): size[k.split('/')[0]] += len(v); cnt[k.split('/')[0]] += 1
    print('new tiles per zoom:', {z: (cnt[z], round(size[z]/1e6, 2)) for z in sorted(cnt, key=int)}, 'MB')
    os.makedirs('out', exist_ok=True)
    open('out/tiles.js', 'w').write('/* generated by build_pwa.py; tiles added later by tools/mapbuild (Overture Maps, ODbL) */\nwindow.SG = window.SG || {};\nSG.MAP_TILES = ' + json.dumps(old, separators=(',', ':')) + ';\n')
    print('total tiles', len(old), 'file MB', round(os.path.getsize('out/tiles.js')/1e6, 2), flush=True)
